name: rok_oauth
description: "Rok Oauth Package Follow Oauth2"
version: 0.1.0
homepage: https://github.com/thachhpn2k/rok_oauth

environment:
  sdk: ^3.2.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
  dio: ^5.7.0

  # A client library for authenticating with a remote service via OAuth2 on behalf of a user, and making authorized HTTP requests with the user's OAuth2 credentials.
  oauth2: ^2.0.3

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.5.0

  # Lock mechanism to prevent concurrent access to asynchronous code.
  synchronized: ^3.3.0+3

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^4.0.0

flutter:
